[package]
name = "pysyn-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
pysyn = { path = ".." }

[[bin]]
name = "parse_bytes"
path = "fuzz_targets/parse_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_structured"
path = "fuzz_targets/parse_structured.rs"
test = false
doc = false
bench = false

[workspace]
